### ISSUE TITLE
Use consistent title case

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#91]
We mix and match right now. This is very nitpicky, but I'm convinced that sentence case is the right choice for almost all of the headings on our site, other than perhaps the titles of the actual interviews if they are written as the form name (rather than a descriptive action sentence).

We recommend sentence case for our interviews for a reason (see https://assemblyline.suffolklitlab.org/docs/style_guide/formatting#use-sentence-case-not-title-case-for-page-headings). There's some evidence it's easier to read. USA.gov recently made this switch: https://blog.usa.gov/making-the-case-for-sentence-case

![image](https://github.com/user-attachments/assets/7e63ee19-c4de-4cd8-8bef-8b810f8dfd37)

![image](https://github.com/user-attachments/assets/df0ee94a-22f8-4058-bd0d-75ea37e6b5f2)

![image](https://github.com/user-attachments/assets/bda4593d-ec90-47fa-a51a-60c1460a28fd)

![image](https://github.com/user-attachments/assets/a76e9af2-09ce-468a-9b6b-0739a09cdbf6)

This tends towards bike-shedding, but: because at least the mix and matching looks a bit sloppy, I recommend we use sentence case.

**Comment by samglover** [comment]
When I was working on the website I found enough inconsistencies across existing LIT Lab materials that I didn't think the guidelines for interviews were meant to apply across our publications. Some examples:

* Most of the documentation uses sentence case for titles and headings, as recommended.
* But almost every [interview title](https://courtformsonline.org/forms) is in title case.
* Most of the [Legal Tech Class materials](https://projects.suffolklitlab.org/legal-tech-class/docs/classes/class-overview) use title case for page titles but sentence case for other headings.
* The [LIT Con 2024 website](https://projects.suffolklitlab.org/LITCon/2024/) used title case for session titles, all-caps for speaker headings, and 

So I chose title case because I prefer it and have been using it throughout the materials I work on.

I prefer titles and headings in title case, but I feel much more strongly that we pick one and stick with it.

I don't find the style guide for interviews persuasive because in interviews most headings aren't functioning as titles. They are questions or statements that function more like body copy. And we clearly don't feel the same about the titles of the interviews themselves, although I'm not sure I see why an interview title should be different than a page title.

I don't think [the USA.gov post](https://blog.usa.gov/making-the-case-for-sentence-case) makes a clear case either way. And for what it's worth, that website is also inconsistent. Most page titles are in sentence case, but the sidebar and footer headings are all in title case. So are all the post tags and the titles of its [about-us](https://www.usa.gov/about) and [media](https://www.usa.gov/media) pages.

In any case, I think USA.gov basically decided they use page titles and headings as sentences, so they were going to capitalize them as sentences. That also feels true for interview headings, which are meant to be read like sentences. It feels true for some of our page titles and headings, too, but not for all of them.

As I said, I feel it's more important to pick one and stick to it across our publications. And we should also include when we do use title case apart from proper names.

**Comment by samglover** [comment]
I think it is only bikeshedding if we keep going. I don't have strong feelings and I think I am persuaded that sentence case is a better fit for our various publications. I'll start a style guide repo and we'll take it from there!
